import { readFileSync, writeFileSync, readdirSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

interface PromptMetadata {
  name: string;
  description: string;
}

/**
 * Extracts metadata from markdown content
 */
function extractMetadata(content: string, filename: string): PromptMetadata {
  // Extract description from context or task_overview sections
  const contextMatch = content.match(/<context>\s*([\s\S]*?)\s*<\/context>/i);
  const overviewMatch = content.match(
    /<task_overview>\s*([\s\S]*?)\s*<\/task_overview>/i
  );

  const description =
    contextMatch?.[1]?.trim() || overviewMatch?.[1]?.trim() || "";

  return {
    name: filename.replace(".md", "").replace(/-/g, "_"),
    description,
  };
}

/**
 * Generate TypeScript code for prompts
 */
function generateQuickGuidesPrompts(): string {
  const promptsDir = join(__dirname, "../assistant-prompts/quickguide");
  const files = readdirSync(promptsDir).filter((file) => file.endsWith(".md"));

  const prompts = files.map((file) => {
    const filePath = join(promptsDir, file);
    const content = readFileSync(filePath, "utf-8");
    const metadata = extractMetadata(content, file);

    return {
      metadata,
      content,
    };
  });

  // Generate TypeScript code
  let code = `/**
 * Auto-generated prompt definitions from markdown files
 * Generated on: ${new Date().toISOString()}
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Run 'npm run generate:prompts' to regenerate
 */


export interface GeneratedPrompt {
  name: string;
  title: string;
  description: string;
  content: string;
}

`;

  // Generate individual prompt constants
  prompts.forEach((prompt) => {
    const constName = prompt.metadata.name.toUpperCase();
    code += `export const ${constName}_PROMPT: GeneratedPrompt = {
  name: "${prompt.metadata.name}",
  title: "${prompt.metadata.name}",
  description: ${JSON.stringify(prompt.metadata.description)},
  content: ${JSON.stringify(prompt.content)},
};

`;
  });

  // Generate the prompts array
  code += `\nexport const GENERATED_PROMPTS: GeneratedPrompt[] = [\n`;
  prompts.forEach((prompt) => {
    const constName = prompt.metadata.name.toUpperCase();
    code += `  ${constName}_PROMPT,\n`;
  });
  code += `];\n`;

  return code;
}

function generateWEResourceLoaderPrompts(): string {
  const promptsDir = join(
    __dirname,
    "../assistant-prompts/resource-loader/web-experimentation"
  );
  const files = readdirSync(promptsDir).filter((file) => file.endsWith(".md"));

  const prompts = files.map((file) => {
    const filePath = join(promptsDir, file);
    const content = readFileSync(filePath, "utf-8");
    const metadata = extractMetadata(content, file);

    return {
      metadata,
      content,
    };
  });

  // Generate TypeScript code
  let code = `/**
 * Auto-generated prompt definitions from markdown files
 * Generated on: ${new Date().toISOString()}
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Run 'npm run generate:prompts' to regenerate
 */


export interface GeneratedPrompt {
  name: string;
  title: string;
  description: string;
  content: string;
}

`;

  // Generate individual prompt constants
  prompts.forEach((prompt) => {
    const constName = prompt.metadata.name.toUpperCase();
    code += `export const ${constName}_PROMPT: GeneratedPrompt = {
  name: "${prompt.metadata.name}",
  title: "${prompt.metadata.name}",
  description: ${JSON.stringify(prompt.metadata.description)},
  content: ${JSON.stringify(prompt.content)},
};

`;
  });

  // Generate the prompts array
  code += `\nexport const GENERATED_PROMPTS: GeneratedPrompt[] = [\n`;
  prompts.forEach((prompt) => {
    const constName = prompt.metadata.name.toUpperCase();
    code += `  ${constName}_PROMPT,\n`;
  });
  code += `];\n`;

  return code;
}

// Main execution
try {
  console.log("Generating prompts from markdown files...\n");

  // Quick Guides Prompts
  const quickGuides = generateQuickGuidesPrompts();
  const quickGuidesOutputPath = join(
    __dirname,
    "../src/prompts/generated/quickGuides.generated.ts"
  );

  mkdirSync(dirname(quickGuidesOutputPath), { recursive: true });

  writeFileSync(quickGuidesOutputPath, quickGuides, "utf-8");

  // Resource Loader Prompts for Web Experimentation
  const resourceLoader = generateWEResourceLoaderPrompts();
  const resourceLoaderOutputPath = join(
    __dirname,
    "../src/prompts/generated/resourceLoader.generated.ts"
  );

  mkdirSync(dirname(resourceLoaderOutputPath), { recursive: true });

  writeFileSync(resourceLoaderOutputPath, resourceLoader, "utf-8");

  console.log(
    `✓ Generated quick guides prompts written to: ${quickGuidesOutputPath}`
  );
  console.log(
    `✓ Generated resource loader prompts written to: ${resourceLoaderOutputPath}`
  );
  console.log("✓ Generation complete!");
} catch (error) {
  console.error("✗ Error generating prompts:", error);
  process.exit(1);
}
